N 10
T 1000
duration 0.01
diffusivity_intra 0.5e-9
diffusivity_extra 2e-9

scheme_file /home/localadmin/Software/Permeable_MCDS_fork/instructions/scheme/PGSE_21_dir_12_b.scheme
exp_prefix /home/localadmin/Software/Permeable_MCDS_fork/output_test/test

<obstacle>
<glials_list>
/home/localadmin/Software/Permeable_MCDS_fork/example_swc_files/single_neuron.swc
permeability global 0.0
</glials_list>
</obstacle>

scale_from_stu 1
write_traj_file 1
write_txt 1
write_bin 0
write_every_nth_step 100
write_location 1

num_process 28
ini_walkers_pos intra

<voxel>
0 0 0
0.35 0.35 0.35
</voxel>
<END>